-- Job log table
--

CREATE TABLE job_logs_202
(
  ID_JOB INT
, CHANNEL_ID VARCHAR(255)
, JOBNAME VARCHAR(255)
, STATUS VARCHAR(15)
, LINES_READ BIGINT
, LINES_WRITTEN BIGINT
, LINES_UPDATED BIGINT
, LINES_INPUT BIGINT
, LINES_OUTPUT BIGINT
, LINES_REJECTED BIGINT
, ERRORS BIGINT
, STARTDATE DATETIME
, ENDDATE DATETIME
, LOGDATE DATETIME
, DEPDATE DATETIME
, REPLAYDATE DATETIME
, LOG_FIELD LONGTEXT
)
;
CREATE INDEX IDX_job_logs_202_1 ON job_logs_202(ID_JOB)
;
CREATE INDEX IDX_job_logs_202_2 ON job_logs_202(ERRORS, STATUS, JOBNAME)
;




-- Transformation log table
--

CREATE TABLE transformation_logs_202
(
  ID_BATCH INT
, CHANNEL_ID VARCHAR(255)
, TRANSNAME VARCHAR(255)
, STATUS VARCHAR(15)
, LINES_READ BIGINT
, LINES_WRITTEN BIGINT
, LINES_UPDATED BIGINT
, LINES_INPUT BIGINT
, LINES_OUTPUT BIGINT
, LINES_REJECTED BIGINT
, ERRORS BIGINT
, STARTDATE DATETIME
, ENDDATE DATETIME
, LOGDATE DATETIME
, DEPDATE DATETIME
, REPLAYDATE DATETIME
, LOG_FIELD LONGTEXT
)
;
CREATE INDEX IDX_transformation_logs_202_1 ON transformation_logs_202(ID_BATCH)
;
CREATE INDEX IDX_transformation_logs_202_2 ON transformation_logs_202(ERRORS, STATUS, TRANSNAME)
;
